#!/bin/sh

OSTYPE=`uname -s`

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

# merge in defaults and keymaps

#export LD_LIBRARY_PATH="/opt/amdgpu-pro/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
#export LIBGL_DRIVERS_PATH="$PACKAGEPATH/usr/lib/x86_64-linux-gnu/dri/"
#export dri_driver="amdgpu"
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

# start some nice programs

#xscreensaver -lock-timeout 3 &
#tkremind&
#xv -quit -root ~/ctwm-themes/du/redbg.png
#xlogo -fg gray80 -bg gray80 -g 1152x24+0-0 &
#xload -hl black -bg gray80 -geometry 32x24-57-0 -fn 5x7 &
#asclock -shape -position +1092+836 -exe timetool&
#asmail -geometry -1-27 > /dev/null&
#/usr/local/bin/ctwm&
#xhost +freja
#xhost +zod
#xhost +balder
#xhost +mucus
#xhost +lex
#xset b 10 100 100
#xterm -iconic -fg black -bg yellow -cr yellow -C -T console -n console

#exec conky -d &
#exec feh --bg-scale .bg.jpg &
#xwinwrap -ni -st -sp -nf -ov -fs -- /usr/local/bin/xscreensaver-hacks/glmatrix -speed 5 -binary -root -window-id WID &
#twm &
#exec xterm -geometry 60x30+400+0 -name login 
#exec xterm -geometry 60x30+400+0 -name ololo

#xinput --set-prop 'TPPS/2 IBM TrackPoint' 'libinput Accel Speed' 1 & # setup speed trackpad
#exec xautolock -time 10 -locker slock &
#exec xscreensaver -no-splash &

setxkbmap -layout "us,ru" -option "grp:caps_toggle,terminate:ctrl_alt_bksp" &
export I3SOCK=${HOME}/.i3/i3.socket
exec /usr/bin/i3
