# This is a zsh startup file.
# Auto cd
setopt autocd
#autocorrect commands
setopt CORRECT_ALL

# don't barf on no-match found.
unsetopt nomatch

# don't barf on bad-pattern.
unsetopt badpattern 

#Operation systems detector
OSTYPE=$(uname -s)

# setopt promptsubst
autoload -U colors && colors
PROMPT="$fg[cyan]%m:%{$fg[white]%}[%(!.%{$fg[red]%}.%{$fg[green]%})%1~%{$fg[white]%}] %D{%H:%M} %(!.%{$fg[red]%}.%{$fg[white]%})%#> %{$reset_color%}"

chpwd() {
	[[ -t 1 ]] || return
	case $TERM in
		sun-cmd) print -Pn "\e]l%~\e\\"
			;;
		*xterm*|rxvt|(dt|k|E)term) print -Pn "\e]2;%~\a"
			;;
	esac
}

case $TERM in
	*xterm*|rxvt) export LC_ALL=ru_RU.UTF-8;;
esac

autoload -U compinit
compinit

#autocomplite hosts form know_hosts


if [ -f $HOME/.ssh/known_hosts ]
then
	local _myhosts
	_myhosts='reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
	zstyle -e ':completion::*:*:*:hosts' hosts ${_myhosts}
fi

zstyle ':completion::complete:*' use-cache 1

# number of lines kept in history
export HISTSIZE=1000
# # number of lines saved in the history after logout
export SAVEHIST=1000
# # location of history
export HISTFILE=$HOME/.zhistory
# append command to history file once executed
setopt inc_append_history

#PATH
PATH="/bin:/usr/bin:/usr/local/bin:/usr/bin/X11:/usr/games"

case ${OSTYPE} in
	FreeBSD) PATH=${PATH}:/usr/sbin:/sbin:/usr/local/sbin;;
esac

#includer *.zsh files from $HOME/.zsh
including(){
	for i in $(ls -1 ${HOME}/.zsh/$1/)
	do
		source ${HOME}/.zsh/$1/${i}
	done
}

# sys includes
including sys

# functions includes
including func

if [ ! -z "${DISPLAY}" -a -z "${MC_SID}" -a "${TERM}" != "screen" ]
then
	function precmd {
		
		local TERMWIDTH
		(( TERMWIDTH = ${COLUMNS} - 1 ))

		###
		# Truncate the path if it's too long.
    
		PR_FILLBAR=""
		PR_PWDLEN=""
    
		local promptsize=${#${(%):---(%n@%M)---()--}}
		local pwdsize=${#${(%):-%~}}
    
		if [[ "$promptsize + $pwdsize" -gt $TERMWIDTH ]]; then
			((PR_PWDLEN=$TERMWIDTH - $promptsize))
		else
			PR_FILLBAR="\${(l.(($TERMWIDTH - ($promptsize + $pwdsize)))..${PR_HBAR}.)}"
		fi
	}


	setopt extended_glob
	preexec () {
	if [[ "$TERM" == "screen" ]]
	then
		local CMD=${1[(wr)^(*=*|sudo|-*)]}
		echo -n "\ek$CMD\e\\"
	fi
	}
fi
