#!/bin/sh

# -*- coding: utf-8 -*-
# vim: set et sw=4 ts=4:

function upscreen() {
    DATE=$(date '+%Y-%m-%d_%H:%M:%S')
    SCREEN="screenshot-${DATE}.png"

    timer() {
        for i in $(jot 5 1 5)
        do
            echo -n "\033[3${i}m ${i} \033[0m"' '
            sleep 1
        done
    }

    if [ -d ${HOME}/Pictures ]
    then
        DSCS="${HOME}/Pictures"
    else
        DSCS="${HOME}"
    fi

    if [ ${OSTYPE} = 'Darwin' ]
    then
        timer
        screencapture -tpng -i ${DSCS}/${SCREEN}
    else
        timer
        scrot -b -q 0 ${DSCS}/${SCREEN}
    fi

    echo 'FIXME: add support to upload file somewhere'
}
