#!/bin/sh

# -*- coding: utf-8 -*-
# vim: set et sw=4 ts=4:

function upkey() {
    if [ -z ${2} ]
    then
        PORT=22
    else
        PORT=${2}
    fi
    if [ -z ${1} ]
    then
        echo "Please specify user@host.ltd and port as the first switch to this script"
    else
        for key in $(find ${HOME}/.ssh -type f -name "id_*.pub"|awk '{printf $1 " "}')
        do
            KEY="${key}"
            if [ -f "${key}" -a -n "${key}" ]
            then
                KEYCODE=$(cat ${KEY})
                ssh -p ${PORT} -q ${1} "test -d ~/.ssh || mkdir ~/.ssh && chmod 700 ~/.ssh; echo "${KEYCODE}" >> ~/.ssh/authorized_keys; chmod 644 ~/.ssh/authorized_keys"
            else
                echo ${KEY} not found
            fi
        done
    fi
}
